# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.models.records_lock_request import RecordsLockRequest

class TestRecordsLockRequest(unittest.TestCase):
    """RecordsLockRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordsLockRequest:
        """Test RecordsLockRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordsLockRequest`
        """
        model = RecordsLockRequest()
        if include_optional:
            return RecordsLockRequest(
                ids = [
                    grax.models.record_lock_id.RecordLockID(
                        id = '', 
                        note = '', )
                    ]
            )
        else:
            return RecordsLockRequest(
        )
        """

    def testRecordsLockRequest(self):
        """Test RecordsLockRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
