# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_search_abort(self) -> None:
        """Test case for search_abort

        Abort search
        """
        pass

    def test_search_create(self) -> None:
        """Test case for search_create

        Create search
        """
        pass

    def test_search_delete(self) -> None:
        """Test case for search_delete

        Delete search
        """
        pass

    def test_search_download(self) -> None:
        """Test case for search_download

        Download search results
        """
        pass

    def test_search_get(self) -> None:
        """Test case for search_get

        Get search
        """
        pass

    def test_search_records(self) -> None:
        """Test case for search_records

        Read search result records
        """
        pass

    def test_searches_list(self) -> None:
        """Test case for searches_list

        List searches
        """
        pass


if __name__ == '__main__':
    unittest.main()
