# coding: utf-8

"""
    GRAX API

    This documents the APIs available in your GRAX backend.  ### Authentication  Generate an API token to authenticate requests from your backend, going to Settings > API Tokens > New Token.  Then supply it with HTTP requests in the `Authorization` header, like:  ``` Authorization: Bearer grax_token_xyz ``` 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.models.record_count import RecordCount

class TestRecordCount(unittest.TestCase):
    """RecordCount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordCount:
        """Test RecordCount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordCount`
        """
        model = RecordCount()
        if include_optional:
            return RecordCount(
                created = 56,
                deleted_by_grax = 56,
                deleted_by_source = 56,
                group = '2024-01-01T00:00Z',
                modified = 56,
                object = ''
            )
        else:
            return RecordCount(
        )
        """

    def testRecordCount(self):
        """Test RecordCount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
