# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.api.delete_forever_api import DeleteForeverApi


class TestDeleteForeverApi(unittest.TestCase):
    """DeleteForeverApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeleteForeverApi()

    def tearDown(self) -> None:
        pass

    def test_deletion_get(self) -> None:
        """Test case for deletion_get

        Get Delete Forever deletion
        """
        pass

    def test_deletion_records_list(self) -> None:
        """Test case for deletion_records_list

        List Delete Forever deletion records
        """
        pass

    def test_deletions_list(self) -> None:
        """Test case for deletions_list

        List Delete Forever deletions
        """
        pass


if __name__ == '__main__':
    unittest.main()
