# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.models.objects_page import ObjectsPage

class TestObjectsPage(unittest.TestCase):
    """ObjectsPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObjectsPage:
        """Test ObjectsPage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObjectsPage`
        """
        model = ObjectsPage()
        if include_optional:
            return ObjectsPage(
                next_page_token = '',
                objects = [
                    grax.models.object.Object(
                        label = '', 
                        name = '', )
                    ]
            )
        else:
            return ObjectsPage(
        )
        """

    def testObjectsPage(self):
        """Test ObjectsPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
