# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.api.records_api import RecordsApi


class TestRecordsApi(unittest.TestCase):
    """RecordsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecordsApi()

    def tearDown(self) -> None:
        pass

    def test_record_children_list(self) -> None:
        """Test case for record_children_list

        List record children
        """
        pass

    def test_record_get(self) -> None:
        """Test case for record_get

        Get record
        """
        pass

    def test_record_versions_list(self) -> None:
        """Test case for record_versions_list

        List record versions
        """
        pass

    def test_records_list(self) -> None:
        """Test case for records_list

        List records
        """
        pass


if __name__ == '__main__':
    unittest.main()
