# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.models.deletion_caller import DeletionCaller

class TestDeletionCaller(unittest.TestCase):
    """DeletionCaller unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeletionCaller:
        """Test DeletionCaller
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeletionCaller`
        """
        model = DeletionCaller()
        if include_optional:
            return DeletionCaller(
                headers = {
                    'key' : [
                        ''
                        ]
                    },
                remote_addr = '',
                user_id = ''
            )
        else:
            return DeletionCaller(
        )
        """

    def testDeletionCaller(self):
        """Test DeletionCaller"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
