# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.models.record_lock_id import RecordLockID

class TestRecordLockID(unittest.TestCase):
    """RecordLockID unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordLockID:
        """Test RecordLockID
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordLockID`
        """
        model = RecordLockID()
        if include_optional:
            return RecordLockID(
                id = '',
                note = ''
            )
        else:
            return RecordLockID(
        )
        """

    def testRecordLockID(self):
        """Test RecordLockID"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
