# coding: utf-8

"""
    GRAX API

    This documents the APIs available in your GRAX backend.  ### Authentication  Generate an API token to authenticate requests from your backend, going to Settings > API Tokens > New Token.  Then supply it with HTTP requests in the `Authorization` header, like:  ``` Authorization: Bearer grax_token_xyz ``` 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.models.unlock_object_records_schema import UnlockObjectRecordsSchema

class TestUnlockObjectRecordsSchema(unittest.TestCase):
    """UnlockObjectRecordsSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnlockObjectRecordsSchema:
        """Test UnlockObjectRecordsSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnlockObjectRecordsSchema`
        """
        model = UnlockObjectRecordsSchema()
        if include_optional:
            return UnlockObjectRecordsSchema(
                ids = [
                    ''
                    ]
            )
        else:
            return UnlockObjectRecordsSchema(
        )
        """

    def testUnlockObjectRecordsSchema(self):
        """Test UnlockObjectRecordsSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
