# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.api.record_lock_api import RecordLockApi


class TestRecordLockApi(unittest.TestCase):
    """RecordLockApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecordLockApi()

    def tearDown(self) -> None:
        pass

    def test_record_lock(self) -> None:
        """Test case for record_lock

        Lock single record
        """
        pass

    def test_record_lock_get(self) -> None:
        """Test case for record_lock_get

        Get record lock
        """
        pass

    def test_record_unlock(self) -> None:
        """Test case for record_unlock

        Unlock single record
        """
        pass

    def test_records_lock(self) -> None:
        """Test case for records_lock

        Lock multiple records
        """
        pass

    def test_records_unlock(self) -> None:
        """Test case for records_unlock

        Unlock multiple records
        """
        pass


if __name__ == '__main__':
    unittest.main()
