# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.api.objects_api import ObjectsApi


class TestObjectsApi(unittest.TestCase):
    """ObjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectsApi()

    def tearDown(self) -> None:
        pass

    def test_objects_list(self) -> None:
        """Test case for objects_list

        List objects
        """
        pass


if __name__ == '__main__':
    unittest.main()
