# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.models.deletion import Deletion

class TestDeletion(unittest.TestCase):
    """Deletion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Deletion:
        """Test Deletion
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Deletion`
        """
        model = Deletion()
        if include_optional:
            return Deletion(
                caller = grax.models.deletion_caller.DeletionCaller(
                    headers = {
                        'key' : [
                            ''
                            ]
                        }, 
                    remote_addr = '', 
                    user_id = '', ),
                cascade = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                force_cascade_objects = [
                    ''
                    ],
                id = '',
                object = '',
                skip_deleted_check = True
            )
        else:
            return Deletion(
        )
        """

    def testDeletion(self):
        """Test Deletion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
