# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.models.records_unlock_request import RecordsUnlockRequest

class TestRecordsUnlockRequest(unittest.TestCase):
    """RecordsUnlockRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordsUnlockRequest:
        """Test RecordsUnlockRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordsUnlockRequest`
        """
        model = RecordsUnlockRequest()
        if include_optional:
            return RecordsUnlockRequest(
                ids = [
                    ''
                    ]
            )
        else:
            return RecordsUnlockRequest(
        )
        """

    def testRecordsUnlockRequest(self):
        """Test RecordsUnlockRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
