# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.models.deletion_records_page import DeletionRecordsPage

class TestDeletionRecordsPage(unittest.TestCase):
    """DeletionRecordsPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeletionRecordsPage:
        """Test DeletionRecordsPage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeletionRecordsPage`
        """
        model = DeletionRecordsPage()
        if include_optional:
            return DeletionRecordsPage(
                next_page_token = '',
                records = [
                    grax.models.deletion_record.DeletionRecord(
                        id = '', 
                        modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        object = '', 
                        purged_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return DeletionRecordsPage(
        )
        """

    def testDeletionRecordsPage(self):
        """Test DeletionRecordsPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
