# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grax.api.auto_backup_api import AutoBackupApi


class TestAutoBackupApi(unittest.TestCase):
    """AutoBackupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutoBackupApi()

    def tearDown(self) -> None:
        pass

    def test_backups_health_get(self) -> None:
        """Test case for backups_health_get

        Get Auto Backup health
        """
        pass


if __name__ == '__main__':
    unittest.main()
