# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from grax.models.record import Record
from grax.models.record_children_page import RecordChildrenPage
from grax.models.record_versions_page import RecordVersionsPage
from grax.models.records_page import RecordsPage

from grax.api_client import ApiClient, RequestSerialized
from grax.api_response import ApiResponse
from grax.rest import RESTResponseType


class RecordsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def record_children_list(
        self,
        org_id: StrictStr,
        object2: StrictStr,
        id: StrictStr,
        mod: Annotated[StrictStr, Field(description="Unused.")],
        object: Annotated[Optional[StrictStr], Field(description="The child object to list.")] = None,
        fields: Annotated[Optional[StrictStr], Field(description="The fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        delete_source: Annotated[Optional[StrictStr], Field(description="The delete source to filter by, can be 'any', 'grax' or 'salesforce'.")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="Maximum number of results to return per page.")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Token returned by previous call to retrieve the subsequent page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RecordChildrenPage:
        """List record children


        :param org_id: (required)
        :type org_id: str
        :param object2: (required)
        :type object2: str
        :param id: (required)
        :type id: str
        :param mod: Unused. (required)
        :type mod: str
        :param object: The child object to list.
        :type object: str
        :param fields: The fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param delete_source: The delete source to filter by, can be 'any', 'grax' or 'salesforce'.
        :type delete_source: str
        :param page_size: Maximum number of results to return per page.
        :type page_size: int
        :param page_token: Token returned by previous call to retrieve the subsequent page.
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._record_children_list_serialize(
            org_id=org_id,
            object2=object2,
            id=id,
            mod=mod,
            object=object,
            fields=fields,
            delete_source=delete_source,
            page_size=page_size,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RecordChildrenPage",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def record_children_list_with_http_info(
        self,
        org_id: StrictStr,
        object2: StrictStr,
        id: StrictStr,
        mod: Annotated[StrictStr, Field(description="Unused.")],
        object: Annotated[Optional[StrictStr], Field(description="The child object to list.")] = None,
        fields: Annotated[Optional[StrictStr], Field(description="The fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        delete_source: Annotated[Optional[StrictStr], Field(description="The delete source to filter by, can be 'any', 'grax' or 'salesforce'.")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="Maximum number of results to return per page.")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Token returned by previous call to retrieve the subsequent page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[RecordChildrenPage]:
        """List record children


        :param org_id: (required)
        :type org_id: str
        :param object2: (required)
        :type object2: str
        :param id: (required)
        :type id: str
        :param mod: Unused. (required)
        :type mod: str
        :param object: The child object to list.
        :type object: str
        :param fields: The fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param delete_source: The delete source to filter by, can be 'any', 'grax' or 'salesforce'.
        :type delete_source: str
        :param page_size: Maximum number of results to return per page.
        :type page_size: int
        :param page_token: Token returned by previous call to retrieve the subsequent page.
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._record_children_list_serialize(
            org_id=org_id,
            object2=object2,
            id=id,
            mod=mod,
            object=object,
            fields=fields,
            delete_source=delete_source,
            page_size=page_size,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RecordChildrenPage",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def record_children_list_without_preload_content(
        self,
        org_id: StrictStr,
        object2: StrictStr,
        id: StrictStr,
        mod: Annotated[StrictStr, Field(description="Unused.")],
        object: Annotated[Optional[StrictStr], Field(description="The child object to list.")] = None,
        fields: Annotated[Optional[StrictStr], Field(description="The fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        delete_source: Annotated[Optional[StrictStr], Field(description="The delete source to filter by, can be 'any', 'grax' or 'salesforce'.")] = None,
        page_size: Annotated[Optional[StrictInt], Field(description="Maximum number of results to return per page.")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Token returned by previous call to retrieve the subsequent page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List record children


        :param org_id: (required)
        :type org_id: str
        :param object2: (required)
        :type object2: str
        :param id: (required)
        :type id: str
        :param mod: Unused. (required)
        :type mod: str
        :param object: The child object to list.
        :type object: str
        :param fields: The fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param delete_source: The delete source to filter by, can be 'any', 'grax' or 'salesforce'.
        :type delete_source: str
        :param page_size: Maximum number of results to return per page.
        :type page_size: int
        :param page_token: Token returned by previous call to retrieve the subsequent page.
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._record_children_list_serialize(
            org_id=org_id,
            object2=object2,
            id=id,
            mod=mod,
            object=object,
            fields=fields,
            delete_source=delete_source,
            page_size=page_size,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RecordChildrenPage",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _record_children_list_serialize(
        self,
        org_id,
        object2,
        id,
        mod,
        object,
        fields,
        delete_source,
        page_size,
        page_token,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if org_id is not None:
            _path_params['orgID'] = org_id
        if object2 is not None:
            _path_params['object'] = object2
        if id is not None:
            _path_params['id'] = id
        if mod is not None:
            _path_params['mod'] = mod
        # process the query parameters
        if object is not None:
            
            _query_params.append(('object', object))
            
        if fields is not None:
            
            _query_params.append(('fields', fields))
            
        if delete_source is not None:
            
            _query_params.append(('deleteSource', delete_source))
            
        if page_size is not None:
            
            _query_params.append(('pageSize', page_size))
            
        if page_token is not None:
            
            _query_params.append(('pageToken', page_token))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'bearer_token'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/salesforce/{orgID}/objects/{object}/records/{id}/versions/{mod}/children',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def record_get(
        self,
        object: Annotated[StrictStr, Field(description="Object name, or '_infer' if you want GRAX to do a lookup based on record ID.")],
        id: Annotated[StrictStr, Field(description="ID of the record.")],
        fields: Annotated[Optional[StrictStr], Field(description="Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Record:
        """Get record


        :param object: Object name, or '_infer' if you want GRAX to do a lookup based on record ID. (required)
        :type object: str
        :param id: ID of the record. (required)
        :type id: str
        :param fields: Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._record_get_serialize(
            object=object,
            id=id,
            fields=fields,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Record",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def record_get_with_http_info(
        self,
        object: Annotated[StrictStr, Field(description="Object name, or '_infer' if you want GRAX to do a lookup based on record ID.")],
        id: Annotated[StrictStr, Field(description="ID of the record.")],
        fields: Annotated[Optional[StrictStr], Field(description="Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Record]:
        """Get record


        :param object: Object name, or '_infer' if you want GRAX to do a lookup based on record ID. (required)
        :type object: str
        :param id: ID of the record. (required)
        :type id: str
        :param fields: Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._record_get_serialize(
            object=object,
            id=id,
            fields=fields,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Record",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def record_get_without_preload_content(
        self,
        object: Annotated[StrictStr, Field(description="Object name, or '_infer' if you want GRAX to do a lookup based on record ID.")],
        id: Annotated[StrictStr, Field(description="ID of the record.")],
        fields: Annotated[Optional[StrictStr], Field(description="Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get record


        :param object: Object name, or '_infer' if you want GRAX to do a lookup based on record ID. (required)
        :type object: str
        :param id: ID of the record. (required)
        :type id: str
        :param fields: Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._record_get_serialize(
            object=object,
            id=id,
            fields=fields,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "Record",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _record_get_serialize(
        self,
        object,
        id,
        fields,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if object is not None:
            _path_params['object'] = object
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        if fields is not None:
            
            _query_params.append(('fields', fields))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'bearer_token'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v2/objects/{object}/records/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def record_versions_list(
        self,
        object: Annotated[StrictStr, Field(description="Object name.")],
        id: Annotated[StrictStr, Field(description="ID of the record.")],
        fields: Annotated[Optional[StrictStr], Field(description="Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        max_items: Annotated[Optional[StrictInt], Field(description="Maximum number of items to return per page. Fewer or zero may be returned.")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Token returned by previous call to retrieve the subsequent page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RecordVersionsPage:
        """List record versions


        :param object: Object name. (required)
        :type object: str
        :param id: ID of the record. (required)
        :type id: str
        :param fields: Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param max_items: Maximum number of items to return per page. Fewer or zero may be returned.
        :type max_items: int
        :param page_token: Token returned by previous call to retrieve the subsequent page.
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._record_versions_list_serialize(
            object=object,
            id=id,
            fields=fields,
            max_items=max_items,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RecordVersionsPage",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def record_versions_list_with_http_info(
        self,
        object: Annotated[StrictStr, Field(description="Object name.")],
        id: Annotated[StrictStr, Field(description="ID of the record.")],
        fields: Annotated[Optional[StrictStr], Field(description="Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        max_items: Annotated[Optional[StrictInt], Field(description="Maximum number of items to return per page. Fewer or zero may be returned.")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Token returned by previous call to retrieve the subsequent page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[RecordVersionsPage]:
        """List record versions


        :param object: Object name. (required)
        :type object: str
        :param id: ID of the record. (required)
        :type id: str
        :param fields: Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param max_items: Maximum number of items to return per page. Fewer or zero may be returned.
        :type max_items: int
        :param page_token: Token returned by previous call to retrieve the subsequent page.
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._record_versions_list_serialize(
            object=object,
            id=id,
            fields=fields,
            max_items=max_items,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RecordVersionsPage",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def record_versions_list_without_preload_content(
        self,
        object: Annotated[StrictStr, Field(description="Object name.")],
        id: Annotated[StrictStr, Field(description="ID of the record.")],
        fields: Annotated[Optional[StrictStr], Field(description="Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        max_items: Annotated[Optional[StrictInt], Field(description="Maximum number of items to return per page. Fewer or zero may be returned.")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Token returned by previous call to retrieve the subsequent page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List record versions


        :param object: Object name. (required)
        :type object: str
        :param id: ID of the record. (required)
        :type id: str
        :param fields: Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param max_items: Maximum number of items to return per page. Fewer or zero may be returned.
        :type max_items: int
        :param page_token: Token returned by previous call to retrieve the subsequent page.
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._record_versions_list_serialize(
            object=object,
            id=id,
            fields=fields,
            max_items=max_items,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RecordVersionsPage",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _record_versions_list_serialize(
        self,
        object,
        id,
        fields,
        max_items,
        page_token,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if object is not None:
            _path_params['object'] = object
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        if fields is not None:
            
            _query_params.append(('fields', fields))
            
        if max_items is not None:
            
            _query_params.append(('maxItems', max_items))
            
        if page_token is not None:
            
            _query_params.append(('pageToken', page_token))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'bearer_token'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v2/objects/{object}/records/{id}/versions',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def records_list(
        self,
        object: Annotated[StrictStr, Field(description="Object name.")],
        fields: Annotated[Optional[StrictStr], Field(description="Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        max_items: Annotated[Optional[StrictInt], Field(description="Maximum number of items to return per page. Fewer or zero may be returned.")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Token returned by previous call to retrieve the subsequent page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RecordsPage:
        """List records


        :param object: Object name. (required)
        :type object: str
        :param fields: Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param max_items: Maximum number of items to return per page. Fewer or zero may be returned.
        :type max_items: int
        :param page_token: Token returned by previous call to retrieve the subsequent page.
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._records_list_serialize(
            object=object,
            fields=fields,
            max_items=max_items,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RecordsPage",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def records_list_with_http_info(
        self,
        object: Annotated[StrictStr, Field(description="Object name.")],
        fields: Annotated[Optional[StrictStr], Field(description="Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        max_items: Annotated[Optional[StrictInt], Field(description="Maximum number of items to return per page. Fewer or zero may be returned.")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Token returned by previous call to retrieve the subsequent page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[RecordsPage]:
        """List records


        :param object: Object name. (required)
        :type object: str
        :param fields: Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param max_items: Maximum number of items to return per page. Fewer or zero may be returned.
        :type max_items: int
        :param page_token: Token returned by previous call to retrieve the subsequent page.
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._records_list_serialize(
            object=object,
            fields=fields,
            max_items=max_items,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RecordsPage",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def records_list_without_preload_content(
        self,
        object: Annotated[StrictStr, Field(description="Object name.")],
        fields: Annotated[Optional[StrictStr], Field(description="Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.")] = None,
        max_items: Annotated[Optional[StrictInt], Field(description="Maximum number of items to return per page. Fewer or zero may be returned.")] = None,
        page_token: Annotated[Optional[StrictStr], Field(description="Token returned by previous call to retrieve the subsequent page.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List records


        :param object: Object name. (required)
        :type object: str
        :param fields: Fields to include in the response. Can be 'all' for all fields, 'name' for the name field, or a comma separated list of field names.
        :type fields: str
        :param max_items: Maximum number of items to return per page. Fewer or zero may be returned.
        :type max_items: int
        :param page_token: Token returned by previous call to retrieve the subsequent page.
        :type page_token: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._records_list_serialize(
            object=object,
            fields=fields,
            max_items=max_items,
            page_token=page_token,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RecordsPage",
            '4XX': "Error",
            '5XX': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _records_list_serialize(
        self,
        object,
        fields,
        max_items,
        page_token,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if object is not None:
            _path_params['object'] = object
        # process the query parameters
        if fields is not None:
            
            _query_params.append(('fields', fields))
            
        if max_items is not None:
            
            _query_params.append(('maxItems', max_items))
            
        if page_token is not None:
            
            _query_params.append(('pageToken', page_token))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            [
                'application/json'
            ]
        )


        # authentication setting
        _auth_settings: List[str] = [
            'bearer_token'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v2/objects/{object}/records',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


