# coding: utf-8

"""
    GRAX API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ChildRecord(BaseModel):
    """
    ChildRecord
    """ # noqa: E501
    delete_source: Optional[StrictStr] = Field(default=None, description="The delete source of the record, if it has been deleted. Can be 'grax' or 'salesforce'.", alias="deleteSource")
    deleted_at: Optional[datetime] = Field(default=None, description="The time the record was deleted, if it has been deleted.", alias="deletedAt")
    fields: Optional[Dict[str, StrictStr]] = Field(default=None, description="The fields of the record, if requested.")
    id: Optional[StrictStr] = Field(default=None, description="The ID of the record.")
    modified_at: Optional[datetime] = Field(default=None, description="The time the record was last modified.", alias="modifiedAt")
    name: Optional[StrictStr] = Field(default=None, description="The name of the record, if requested.")
    object: Optional[StrictStr] = Field(default=None, description="The object of the record.")
    salesforce_url: Optional[StrictStr] = Field(default=None, description="The Salesforce URL of the record.", alias="salesforceURL")
    __properties: ClassVar[List[str]] = ["deleteSource", "deletedAt", "fields", "id", "modifiedAt", "name", "object", "salesforceURL"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChildRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChildRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deleteSource": obj.get("deleteSource"),
            "deletedAt": obj.get("deletedAt"),
            "fields": obj.get("fields"),
            "id": obj.get("id"),
            "modifiedAt": obj.get("modifiedAt"),
            "name": obj.get("name"),
            "object": obj.get("object"),
            "salesforceURL": obj.get("salesforceURL")
        })
        return _obj


